In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
from IPython.display import display, HTML

In [9]:
import math
import matplotlib.pyplot as plt

In [5]:
np.sin(np.pi)

1.2246467991473532e-16

In [14]:
my_list = list(range(1,100))
print(my_list)
np.array(my_list)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
# NumPy array - numpy has specific typing unlike the vanialla python list

NUMPY linspace 
https://numpy.org/doc/stable/reference/generated/numpy.linspace.html

In [17]:
array0 = np.linspace(1, 101, num = 101, dtype = int)
array0

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101])

In [20]:
print(array0.shape) # no more len
len(array0)

(101,)


101

In [21]:
# indexing from the python list

In [23]:
array0[3] # same as a list
array0[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
array0[(array0 < 10) | (array0 > 90 )]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101])

In [28]:
array_test = np.where((array0 < 10) | (array0 > 90 ))
array_test
array0[array_test]

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  91,  92,  93,  94,
        95,  96,  97,  98,  99, 100, 101])